# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.20/Modules/CheckIncludeFile.cxx.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.20/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jordanevans/Documents/ASPIK/ALL_SDK/VST_SDK/VST3_SDK/pluginterfaces/CMakeLists.txt))

/Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter/mac_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter -B/Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter/mac_build
