# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter/cmake/au_cmake/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter/project_source/cmake/au_cmake/CMakeLists.txt))

/Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter/mac_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter -B/Users/jordanevans/Documents/ASPIK/ALL_SDK/myprojects/JExciter/mac_build
